enyo.depends(
	"source/leaflet.js",
	"source/TileLayer.MBTiles.js",
	"source/WebOSM.js",
	"source/ActionBar.js",
	"source/MapControl.js",
	"source/bluetoothGPS.js",
	"source/Search.js",
	"source/Route.js",
	"source/Toaster.js",
	"source/AboutDialog.js",
	"source/database.js",
	"css/leaflet.css"
);
